
name: GHA summary table
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0 
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0 
